version: "3.8"

services:
  cyberguardian:
    container_name: cyberguardian
    build:
      context: ./cyberguardian
      dockerfile: Dockerfile
    volumes:
      - ./cyberguardian:/app
    environment:
      - NODE_ENV=production
    networks:
      - nginxproxymanager_default
    restart: unless-stopped

networks:
  nginxproxymanager_default:
    external: true
