version: "3.8"

services:
  cyberguardian-server:
    container_name: cyberguardian-server
    build:
      context: ./cyberguardian-server
      dockerfile: Dockerfile
    ports:
      - "4000:4019"
    volumes:
      - ./cyberguardian-server:/app
    networks:
      - cybertools_network
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    # volumes:
    #   - cyberguardian-server:/data/db
    networks:
      - cybertools_network
    restart: unless-stopped

networks:
  cybertools_network:
    driver: bridge

volumes:
  cyberguardian-server:
