version: "3.8"

services:
  cyberguardian:
    container_name: cyberguardian
    build:
      context: ./cyberguardian
      dockerfile: Dockerfile
    volumes:
      - ./cyberguardian:/app
      - cyberguardian_node_modules:/app/node_modules
      - cyberguardian_next:/app/.next
    environment:
      - NODE_ENV=development
    networks:
      - nginxproxymanager_default
    restart: unless-stopped

networks:
  nginxproxymanager_default:
    external: true
volumes:
  cyberguardian_node_modules:
  cyberguardian_next:
