import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

/**_document.tsx:
 * 
Purpose: _document.tsx is used to customize the HTML document that Next.js renders on the server.
 It allows you to add custom HTML, metadata, or scripts that should be included in the initial HTML document.

Features:
Custom HTML: You can override the default HTML structure generated by Next.js and add custom elements,
 attributes, or scripts.

Metadata: _document.tsx is a good place to define metadata such as <title>, <meta>,
 or <link> tags for SEO optimization.

Server-side Rendering: _document.tsx runs on the server and generates the initial HTML markup for each page,
 allowing you to customize server-rendered content.

Example Use Cases: Adding custom <meta> tags for SEO, including external scripts or fonts,
 setting up server-side rendering for styled components or other CSS-in-JS libraries. */
